### ISSUE TITLE
multi-survey vs. single-survey tpl

### ISSUE THREAD

**Issue by JaneSullivan-NOAA** [JaneSullivan-NOAA/bsai_orox#1]
When I adopted this assessment it used the multi-survey version of the tpl and only one logsdlam was estimated (i.e. process error shared across surveys). The T4/5 non-working group is exploring differences between the multi-survey version of the tpl and the single survey tpl [https://github.com/afsc-assessments/SurveyAverageRandomEffects/blob/master/src/re.tpl]

The explorations branch does 2 things:

1. added a run_sre_model (run single species RE model) fxn to re_helper.R
2. added a section in 1_biomass.R called logsdlam [https://github.com/JaneSullivan-NOAA/bsai_orox/blob/c06e12845c8143687529159a5e4d38b9a3af6fa2/R/1_biomass.R#L885](url) that compares (1) multi-survey with single logsdlam, (2) multi-survey with a logsdlam for each survey, and (3) single survey tpl for each survey separately

To reproduce output, open R/1_biomass.R, run lines 1-96 (create data_sst_nonSST object), then jump to logsdlam section (line 885) to run different RE versions. The multi-survey tpl is admb/RE.tpl and the single-survey tpl is admb/RES.tpl. ADMB dat files and all output in results/2020/ 

![logsdlam_by_tpl_bsai_orox](https://user-images.githubusercontent.com/68303089/121716671-c4bec180-ca8c-11eb-955a-b7c239ed7b15.png)

**Comment by Cole-Monnahan-NOAA** [comment]
@JaneSullivan-NOAA I'm not able to reproduce this for the SST data file. They match to the precision I'd expect depending on different initial values and convergence criteria etc. When I run it in a new folder I get this:

````
## Output from multivariate model with a process error for each
## survey
name       value      std.dev
logSdLam -2.0735e+00 3.0603e-01
logSdLam -2.2211e+00 3.8659e-01
logSdLam -1.8617e+00 8.3046e-01

## Run the same data through the univariate RE model separately
logSdLam -2.0733e+00 3.0603e-01
logSdLam -2.2208e+00 3.8659e-01
logSdLam -1.8626e+00 8.3043e-01

## now take the multivariate model and only put in a single
## survey at a time
logSdLam -2.0724e+00 3.0604e-01
logSdLam -2.2200e+00 3.8661e-01
logSdLam -1.8617e+00 8.3046e-01
````

When I run it combined mode I get this:
logSdLam -2.1095e+00 2.3650e-01 
which makes a lot of sense to me as the combined SD is about in the middle of the separate ones.

So I'm not sure what is going on with your run. I'm pretty convinced that they behave as they should.

**Comment by JaneSullivan-NOAA** [comment]
@Cole-Monnahan-NOAA well that was a blast!

Ok so the deal was I failed to include all of the -9's for the missing survey years. When I added those in, everything was fixed. It is pretty interesting that if the recommendation coming out of this Tier 5 improvement group is to use the single survey model then I'll have to deal with non-convergence for non-SST in the EBS slope survey.

```
   species region    tpl               n_logsdlam                      logsdlam      sd
   <chr>   <ord>     <chr>             <chr>                              <dbl>   <dbl>
 1 non-SST AI        multi-survey tpl  logsdlam for each survey          -0.461  0.356 
 2 non-SST AI        single survey tpl logsdlam for each survey          -0.461  0.356 
 3 non-SST SBS       multi-survey tpl  logsdlam for each survey          -0.156  0.307 
 4 non-SST SBS       single survey tpl logsdlam for each survey          -0.156  0.307 
 5 non-SST EBS_SLOPE multi-survey tpl  logsdlam for each survey          -5      0.0143
 6 non-SST EBS_SLOPE single survey tpl logsdlam for each survey          -6.92  87.0   
 7 non-SST EBS_SHELF multi-survey tpl  logsdlam for each survey          -0.216  0.301 
 8 non-SST EBS_SHELF single survey tpl logsdlam for each survey          -0.216  0.301 
 9 non-SST COMBINED  multi-survey tpl  single logsdlam for all surveys   -0.355  0.185 
10 SST     AI        multi-survey tpl  logsdlam for each survey          -2.07   0.306 
11 SST     AI        single survey tpl logsdlam for each survey          -2.07   0.306 
12 SST     SBS       multi-survey tpl  logsdlam for each survey          -1.86   0.830 
13 SST     SBS       single survey tpl logsdlam for each survey          -1.86   0.830 
14 SST     EBS_SLOPE multi-survey tpl  logsdlam for each survey          -2.22   0.387 
15 SST     EBS_SLOPE single survey tpl logsdlam for each survey          -2.22   0.387 
16 SST     COMBINED  multi-survey tpl  single logsdlam for all surveys   -2.11   0.236 
```

**Comment by Cole-Monnahan-NOAA** [comment]
I'm not quite sure why the -9s would matter since they're ignored in the TPL. I'm probably missing something, so if it makes sense to you then I'm happy.
